#!/bin/env python

# Patch all excalidraw SVG drawings to fix
# distorted LaTeX in the SVGs by replacing
# `preserveAspectRatio="none"`
# into `preserveAspectRatio="true"`
# Note: this is a Python script

import re
import glob
import os

pattern = re.compile(r"preserveAspectRatio=.none.", flags=re.MULTILINE)
substitution = "preserveAspectRatio=\"true\""

for drawing in glob.glob("**/*.excalidraw.svg", recursive=True):
    with open(drawing, "r") as f:
        raw_markup = f.read()
        replacement = pattern.sub(substitution, raw_markup)
    with open(drawing, "w") as f:
        f.write(replacement)
